---
author: 
  - name: Teng-Leong Chew
    orcid: 0000-0002-3139-7560
    affiliations:
      - name: HHMI Janelia Research Campus
        state: VA
        country: USA
        postal-code: 20147
contributors: [
  ""
]
subtitle: AI at Every Stage of the Microscopy Workflow
---

# Introduction

- Why is this textbook needed - what gap we are trying to fill
- What this book tries to accomplish
  - Demystifying AI
  - Roadmap for the book: two main pillars 
    - ML/AI in image acquisition - how AI/ML alter microscope capabilities
    - ML/AI in image processing analysis
    - (a very brief synopsis of each chapter will be included)
- Highlight open source resources
- Target audience: Biologists & microscopists
    - (i) reduce the initial trepidation to explore AI/ML
    - (ii) know where to find open source tools
    - (iii) can communicate with the right vocabulary with bioimage analysts

Topics suggested during the authors' meetings: Discuss that AI is not always solution and talk about when it is actually useful. Discuss that there are many types of microscopy images and each will have their own AI considerations (e.g., imaging modality, 2D vs 3D, static vs time lapse).

## Bibliography and Citations

To cite a research article, add it to references.bib and then refer to the citation key. For example, reference @stringer2021 refers to CellPose and reference @von_chamier2021 refers to ZeroCostDL4Mic.

## Quarto has additional features.

You can learn more about markdown options and additional Quarto features in the [Quarto documentation](https://quarto.org/docs/authoring/markdown-basics.html).  One example that you might find interesting is the option to include callouts in your text. These callouts can be used to highlight potential pitfalls or provide additional optional exercises that the reader might find helpful. Below are examples of the types of callouts available in Quarto.

::: {.callout-note}
Note that there are five types of callouts, including:
`note`, `tip`, `warning`, `caution`, and `important`. They can default to open (like this example) or collapsed (example below).
:::

::: {.callout-tip collapse="true"}
These could be good for extra material or exercises.
:::

::: {.callout-caution}
There are caveats when applying these tools.
:::

::: {.callout-warning}
Be careful to avoid hallucinations.
:::

::: {.callout-important}
This is key information.
:::