---
author: 
  - name: Stephan Saalfeld
    orcid: 0000-0002-4106-1761
    affiliations:
      - name: HHMI Janelia Research Campus
        state: VA
        country: USA
        postal-code: 20147
  - name: Add any co-authors as appropriate
    orcid: 
    affiliations:
      - name: 
        state: 
        country: 
        postal-code: 
subtitle: An Introduction to Artificial Intelligence
---

# AI Primer {#sec-primer}
<!--Your first header will be the chapter's upper-level table of contents title.-->
<!--If you'd like to have a subtitle, include it in the Quarto header above -->

Starting prompt for this chapter: Chapter 2 demystifies Artificial Intelligence for microscopy users. It should define terms (e.g., machine/deep learning, supervised/unsupervised learning) without programming details such that an educated scientist without AI experience can understand how these concepts apply to microscopy in life sciences. The use-cases and strengths of different approaches for different applications should be discussed (e.g., contrasting unsupervised clustering vs supervised segmentation). This chapter should broadly introduce image restoration and segmentation, as they will be themes throughout.

Suggestion from authors' meetings: This chapter can draw on the outlines from other chapters to introduce key topics for the following chapters.

## Demystifying AI
* What is AI? What is ML?
  * Distinguish different subcategories of AI

## Broadstrokes "definitions" of various AI/ML techniques

* Contrast [supervised](glossary.qmd#supervised-learning) vs unsupervised learning
* What are Neural Networks and Deep Learning?
  * Introduce backpropagation and error metrics
  * How do Convolutional Neural Networks fit in?
* Tie examples back to biology and microscopy, where possible
* Provide explanations/cases of when one approach would work better than others

## The importance of Training Data (set the stage for Chapter 5)

* What doest training data look like? 
  * Inputs and ground truth
  * Microscopy training data
    * Pairs of images
* What does a "good" training set look like?
  * Define balanced training sets
  * Explain why this is necessary

## Introduce image restoration (set the stage for Chapter 6)
* Unsupervised e.g. Noise2Void
* Supervised e.g. CARE
* This is important for microscopy because you can restore data quality or compensate for suboptimal imaging conditions
* This is an example of AI/ML adding to existing microscopy workflows

## Introduce segmentation (set the stage for Chapters 4, 8 and 9)
* Compare and contrast use cases
  * Unsupervised clustering for H&E
  * Supervised segmentation for analyzing developing embryos
* This is an opportunity to discuss choosing the correct technique for a given task

## What AI is not (set the stage for Chapter 10)
* A replacement for sound scientific and biological reasoning
* Infallible
  * Introduce the concepts of errors, hallunications, etc.
    * Where/why they arise
    * How to diagnose them
    * Remedies
* Any other caveats 

## Conclusion
* Acknowledge that this is a lot of content
  * Point to the glossary as a reference
  * Other references and resources
* The following chapters will provide concrete examples of using these techniques
