---
editors: [
  "Teng-Leong Chew",
  "Rachel Lee",
  "Owen Puls"
]
affiliation: [
  "HHMI Janelia Research Campus"
]
# doi: "tempDOI"
format:
  html:
    toc: false
    template-partials:
      - settings/title-metadata.html
---


# Welcome {.unnumbered}

_AI in Microscopy_ is an interactive online textbook intended to introduce biologists and microscopists to the fundamentals of artificial intelligence and machine learning.

The table of contents on the left can be used to navigate the book.  Subsections of each chapter appear as a clickable menu on the right side of each chapter page. Key terms in each chapter are highlighted as links to the Glossary page.  A free PDF of the textbook can be downloaded from the upper left menu, which also contains a toggle for using the website in dark mode.

The source code for this textbook is available on [GitHub](https://github.com/aicjanelia/BioImagingAI/). All content is licensed under [BSD 3-Clause](https://github.com/aicjanelia/BioImagingAI/?tab=BSD-3-Clause-1-ov-file), except where noted otherwise.

:::{.callout-caution}
_AI in Microscopy_ is currently under construction and some chapters are incomplete. This page will continue to be updated as the textbook progresses.
:::

<!-- - How to cite the book. -->
